# Generated by Django 4.1.3 on 2024-05-24 18:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo_Empresa',
            fields=[
                ('cod_art', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo de la Maquinaria de la empresa')),
                ('descrip_art', models.TextField(verbose_name='Descripción')),
                ('marca_art', models.CharField(max_length=20, verbose_name='Marca')),
                ('modelo_art', models.CharField(max_length=20, verbose_name='Modelo')),
                ('precio', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(1)], verbose_name='Precio')),
                ('stock', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(1)], verbose_name='Stock')),
                ('fecha_duracion', models.DateField(verbose_name='Tiempo de desuso')),
            ],
            options={
                'verbose_name': 'Articulo de la Empresa',
                'verbose_name_plural': 'Articulos de la Empresa',
                'ordering': ['stock'],
            },
        ),
        migrations.CreateModel(
            name='Articulo_Productor',
            fields=[
                ('cod_artprod', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('descrip_artprod', models.TextField(verbose_name='Descripción')),
                ('marca_art', models.TextField(blank=True, null=True, verbose_name='Marca')),
                ('modelo_art', models.TextField(blank=True, null=True, verbose_name='Modelo')),
                ('año_artprod', models.CharField(choices=[('2024', '2024'), ('2023', '2023'), ('2022', '2022'), ('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013'), ('2012', '2012'), ('2011', '2011'), ('2010', '2010'), ('2009', '2009'), ('2008', '2008'), ('2007', '2007'), ('2006', '2006'), ('2005', '2005'), ('2004', '2004'), ('2003', '2003'), ('2002', '2002'), ('2001', '2001'), ('2000', '2000'), ('1999', '1999'), ('1998', '1998'), ('1997', '1997'), ('1996', '1996'), ('1995', '1995'), ('1994', '1994'), ('1993', '1993'), ('1992', '1992'), ('1991', '1991'), ('1990', '1990'), ('1989', '1989'), ('1988', '1988'), ('1987', '1987'), ('1986', '1986'), ('1985', '1985'), ('1984', '1984'), ('1983', '1983'), ('1982', '1982'), ('1981', '1981'), ('1980', '1980'), ('1979', '1979'), ('1978', '1978'), ('1977', '1977'), ('1976', '1976'), ('1975', '1975'), ('1974', '1974'), ('1973', '1973'), ('1972', '1972'), ('1971', '1971'), ('1970', '1970'), ('1969', '1969'), ('1968', '1968'), ('1967', '1967'), ('1966', '1966'), ('1965', '1965'), ('1964', '1964'), ('1963', '1963'), ('1962', '1962'), ('1961', '1961'), ('1960', '1960'), ('1959', '1959'), ('1958', '1958'), ('1957', '1957'), ('1956', '1956'), ('1955', '1955'), ('1954', '1954'), ('1953', '1953'), ('1952', '1952'), ('1951', '1951'), ('1950', '1950'), ('1949', '1949'), ('1948', '1948'), ('1947', '1947'), ('1946', '1946'), ('1945', '1945'), ('1944', '1944'), ('1943', '1943'), ('1942', '1942'), ('1941', '1941'), ('1940', '1940'), ('1939', '1939'), ('1938', '1938'), ('1937', '1937'), ('1936', '1936'), ('1935', '1935'), ('1934', '1934'), ('1933', '1933'), ('1932', '1932'), ('1931', '1931'), ('1930', '1930'), ('1929', '1929'), ('1928', '1928'), ('1927', '1927'), ('1926', '1926'), ('1925', '1925'), ('1924', '1924'), ('1923', '1923'), ('1922', '1922'), ('1921', '1921'), ('1920', '1920'), ('1919', '1919'), ('1918', '1918'), ('1917', '1917'), ('1916', '1916'), ('1915', '1915'), ('1914', '1914'), ('1913', '1913'), ('1912', '1912'), ('1911', '1911'), ('1910', '1910'), ('1909', '1909'), ('1908', '1908'), ('1907', '1907'), ('1906', '1906'), ('1905', '1905'), ('1904', '1904'), ('1903', '1903'), ('1902', '1902'), ('1901', '1901'), ('1900', '1900')], max_length=4, verbose_name='Año')),
            ],
            options={
                'verbose_name': 'Articulos del Productor',
                'verbose_name_plural': 'Articulos de los Productor',
                'ordering': ['cod_artprod'],
            },
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('cod_cult', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('nom_cult', models.CharField(max_length=30, unique=True, verbose_name='Cultivo')),
            ],
            options={
                'verbose_name': 'Cultivo',
                'verbose_name_plural': 'Cultivos',
                'ordering': ['nom_cult'],
            },
        ),
        migrations.CreateModel(
            name='Marca_Articulo',
            fields=[
                ('cod_marca', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('marca_art', models.CharField(max_length=30, unique=True, verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Marca del articulo',
                'verbose_name_plural': 'Marca de los articulos',
                'ordering': ['marca_art'],
            },
        ),
        migrations.CreateModel(
            name='Modelo_Articulo',
            fields=[
                ('cod_modelo', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('modelo_art', models.CharField(max_length=20, unique=True, verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Modelo del articulo',
                'verbose_name_plural': 'Modelo de los articulos',
                'ordering': ['modelo_art'],
            },
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('cod_prod', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('tipo_cedula_prod', models.CharField(max_length=2)),
                ('cedula_prod', models.CharField(max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='Cedula')),
                ('nom_prod', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nombre')),
                ('apell_prod', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Apellido')),
                ('direccion_prod', models.TextField(verbose_name='Dirección')),
                ('tipo_telef_prod', models.CharField(blank=True, max_length=5, null=True)),
                ('telef_prod', models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='Telefono local')),
                ('tipo_movil_prod', models.CharField(max_length=5)),
                ('movil_prod', models.CharField(max_length=7, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='Telefono movil')),
                ('correo_prod', models.EmailField(max_length=100, unique=True, verbose_name='Correo electrónico')),
            ],
            options={
                'verbose_name': 'Productor',
                'verbose_name_plural': 'Productores',
                'ordering': ['cedula_prod'],
            },
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('cod_res', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('tipo_cedula_res', models.CharField(max_length=2)),
                ('cedula_res', models.CharField(max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='Cedula')),
                ('nom_res', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nombre')),
                ('apell_res', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Apellido')),
                ('direccion_res', models.TextField(verbose_name='Dirección')),
                ('tipo_telef_res', models.CharField(blank=True, max_length=5, null=True)),
                ('telef_res', models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='Telefono local')),
                ('tipo_movil_res', models.CharField(max_length=5)),
                ('movil_res', models.CharField(max_length=7, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='Telefono movil')),
                ('correo_res', models.EmailField(max_length=100, unique=True, verbose_name='Correo electrónico')),
            ],
            options={
                'verbose_name': 'Responsable',
                'verbose_name_plural': 'Responsables',
                'ordering': ['cedula_res'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('cod_usuario', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Nombre de usuario')),
                ('nombre', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Apellido')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Correo electrónico')),
                ('imagen', models.ImageField(blank=True, max_length=200, null=True, upload_to='perfil/', verbose_name='Foto de perfil')),
                ('usuario_administrador', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unidad_Productiva',
            fields=[
                ('cod_uni', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('tipo_rif', models.CharField(max_length=2)),
                ('rif_uni', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9)], verbose_name='Rif de la unidad productiva')),
                ('nom_prod', models.TextField(blank=True, null=True, verbose_name='Nombre')),
                ('apell_prod', models.TextField(blank=True, null=True, verbose_name='Apellido')),
                ('nom_res', models.TextField(blank=True, null=True, verbose_name='Nombre')),
                ('apell_res', models.TextField(blank=True, null=True, verbose_name='Apellido')),
                ('nom_uni', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nombre de la unidad')),
                ('estado_uni', models.CharField(blank=True, max_length=30, null=True, verbose_name='Estado')),
                ('municipio_uni', models.CharField(blank=True, max_length=30, null=True, verbose_name='Municipio')),
                ('parroquia_uni', models.CharField(blank=True, max_length=30, null=True, verbose_name='Parroquia')),
                ('cod_prod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Project.productor', verbose_name='Productor')),
                ('cod_res', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Project.responsable', verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Unidad Productiva',
                'verbose_name_plural': 'Unidades Productivas',
                'ordering': ['rif_uni'],
            },
        ),
        migrations.CreateModel(
            name='Necesidad_Productor',
            fields=[
                ('cod_nec', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo de la necesidad')),
                ('fecha_nec', models.DateField(verbose_name='Fecha de la necesidad')),
                ('nom_uni', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre de la Unidad')),
                ('descrip_art', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('marca_art', models.TextField(blank=True, max_length=20, null=True, verbose_name='Marca')),
                ('modelo_art', models.TextField(blank=True, max_length=20, null=True, verbose_name='Modelo')),
                ('canti_art', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(1)], verbose_name='Cantidad del articulo')),
                ('cod_art', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Project.articulo_empresa', verbose_name='Articulo de la Empresa')),
                ('cod_uni', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Project.unidad_productiva', verbose_name='Codigo de la Unidad')),
            ],
            options={
                'verbose_name': 'Necesidad del productor',
                'verbose_name_plural': 'Necesidades del productor',
                'ordering': ['fecha_nec'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('cod_inv', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo del inventario')),
                ('descrip_artprod', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('cod_marca', models.TextField(blank=True, null=True, verbose_name='Marca')),
                ('cod_modelo', models.TextField(blank=True, null=True, verbose_name='Modelo')),
                ('cant_artprod', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('nom_uni', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre de la Unidad')),
                ('cod_artprod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Project.articulo_productor', verbose_name='Codigo del Articulo')),
                ('cod_uni', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Project.unidad_productiva', verbose_name='Rif de la Unidad')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'ordering': ['cod_artprod'],
            },
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('cod_det', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('areahectarea_pro', models.TextField(verbose_name='Area del Cultivo')),
                ('nom_cult', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cultivo')),
                ('cod_cult', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Project.cultivo', verbose_name='Cultivo')),
            ],
            options={
                'verbose_name': 'Detalle',
                'verbose_name_plural': 'Detalles',
                'ordering': ['cod_det'],
            },
        ),
        migrations.CreateModel(
            name='Censo',
            fields=[
                ('cod_cen', models.AutoField(primary_key=True, serialize=False, verbose_name='codigo')),
                ('fecha_cen', models.DateField(auto_now=True, verbose_name='Fecha del censo')),
                ('nom_uni', models.TextField(blank=True, null=True, verbose_name='Nombre de la unidad')),
                ('tipo_det', models.CharField(max_length=2, verbose_name='Opcion de detalles')),
                ('nom_cult', models.TextField(blank=True, null=True, verbose_name='Cultivo')),
                ('areahectarea_pro', models.TextField(blank=True, null=True, verbose_name='Area del Cultivo')),
                ('ganado_leche', models.CharField(max_length=2, verbose_name='Producción de leche')),
                ('ganado_carne', models.CharField(max_length=2, verbose_name='Producción de carne')),
                ('cod_det', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Project.detalle', verbose_name='Producción de cultivo')),
                ('cod_uni', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Project.unidad_productiva', verbose_name='Rif de la unidad')),
            ],
            options={
                'verbose_name': 'Censo',
                'verbose_name_plural': 'Censos',
                'ordering': ['fecha_cen'],
            },
        ),
        migrations.AddField(
            model_name='articulo_productor',
            name='cod_marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Project.marca_articulo', verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='articulo_productor',
            name='cod_modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Project.modelo_articulo', verbose_name='Modelo'),
        ),
    ]
